#########################--mysql--########################
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 123456
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      password: guest
      username: guest
      virtual-host: /
      listener:
        auto-startup: true
server:
  port: 8080
  display-name: "liubo-loan"
  tomcat:
    accesslog:
      directory: /opt/logs/
      prefix: acesslog
      suffix: .log
        # 使用druid数据源
#########################--mysql end--########################
